### PR TITLE
fix: Argument::that allows params

### LINKED ISSUE #72: [Prophecy][False Positive] Argument::that problems
> InvalidArgument - tests/Feature/Cart/CartItems/GSuiteCartItemTest.php:87:122 - Argument 1 of Prophecy\Argument::that expects callable():bool, Closure(mixed):bool provided

The callable passed to `Argument::that` is allowed to have parameters I believe. If I delete the stub entirely, my test passes however then we lose the benefit of the `bool` typehint.

How do we inform  psalm that any # of mixed params can be parameters of the callable?

### PR DESCRIPTION
**Pull request by mr-feek**
fixes #72

### CODE REVIEW

**Comment by weirdan** [comment]
Mind adding a test for this?

**Comment by weirdan** [comment]
Also you may want to rebase - I've just fixed tests in master

**Comment by mr-feek** [comment]
sure, comin right up

**Comment by mr-feek** [comment]
how's that lookin @weirdan ? I figured Prophecy was worthy of its own test case, since it's relatively independent of phpunit

**Comment by weirdan** [comment]
Looking good!

**Comment by weirdan** [comment]
Released in [0.10.1](https://github.com/psalm/psalm-plugin-phpunit/releases/tag/0.10.1).

**Pull request merged**
