### PR TITLE
Assert functions are public and static

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by oliverklee** [comment]
LGTM.

@weirdan Would you mind taking a look whether this PR can be merged?

**Comment by weirdan** [comment]
Please rebase

**Comment by snapshotpl** [comment]
@weirdan done

**Comment by weirdan** [comment]
Travis build passed: https://travis-ci.org/github/psalm/psalm-plugin-phpunit/builds/669822031

@muglug can you check why travis results are not reported?

**Comment by weirdan** [comment]
Tagged [0.9.2](https://github.com/psalm/psalm-plugin-phpunit/releases/tag/0.9.2).

**Pull request merged**
