### PR TITLE
Immutable refactoring

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by orklah** [comment]
Thanks, but we'll need to make the split for Psalm 5 with this. We can't make a release compatible with both

**Comment by danog** [comment]
This should do the trick (I hope :)

**Comment by orklah** [comment]
Could you check both with PackageVersion? It will be easier to find in the future when we want to remove 4.x

**Comment by danog** [comment]
Done!

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
